version: '3'
services:
  date:
    image: seaside-debian-slim
    deploy:
      replicas: 4
      labels:
        traefik.enable: "true"
        traefik.port: 7777
        traefik.frontend.rule: "HostRegexp:{catchall:.*}" # Match all requests
  balancer:
    image: traefik:v1.7
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Required because of docker backend, so traefik can get docker data.
      - ./traefik.toml:/traefik.toml:ro # Traefik configuration file
